# Generated by Django 4.1.7 on 2023-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='200', max_length=15, verbose_name='Order Status'),
            preserve_default=False,
        ),
    ]
