# Generated by Django 4.1.7 on 2023-03-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('from_email', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('message', models.TextField(max_length=500)),
                ('name', models.EmailField(max_length=20)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
